"use strict";
exports.__esModule = true;
var cadres_1 = require("./cadres");
var employeemanager_1 = require("./employeemanager");
var cadres1 = new cadres_1.Cadres(2, "Lê Trung Thanh", 20, "nam", "hà nội");
var cadres2 = new cadres_1.Cadres(4, "Lê An Hoa", 27, "nữ", "hà nội");
var cadres3 = new cadres_1.Cadres(6, "Lê Hân An", 15, "nữ", "hà nội");
employeemanager_1.EmployeeManager.add(cadres1);
employeemanager_1.EmployeeManager.add(cadres2);
employeemanager_1.EmployeeManager.add(cadres3);
employeemanager_1.EmployeeManager.show();
console.log("-------tìm theo tên");
console.log(employeemanager_1.EmployeeManager.searchByName("Lê An Hoa"));
console.log("----sau xóa----");
employeemanager_1.EmployeeManager.deleteById(4);
employeemanager_1.EmployeeManager.show();
console.log("----sau sua----");
employeemanager_1.EmployeeManager.edit(6, "đức");
